{{- if .Values.custom404.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-404-page
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-404-page
  template:
    metadata:
      labels:
        app: custom-404-page
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: html-content
        configMap:
          name: custom-404-html
      - name: nginx-config
        configMap:
          name: custom-404-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: custom-404-service
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  selector:
    app: custom-404-page
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-404-html
  namespace: {{ .Release.Namespace | default "default" }}
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>404 - XQUARE Infrastructure</title>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
        <style>
            * {
                margin: 0;
                padding: 0;
                box-sizing: border-box;
            }
            
            body {
                font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                background: #0d1117;
                color: #e6edf3;
                overflow-x: hidden;
                line-height: 1.6;
            }
            
            .background {
                position: fixed;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                z-index: -1;
                background: radial-gradient(circle at 25% 25%, rgba(120, 119, 198, 0.15) 0%, transparent 70%),
                            radial-gradient(circle at 75% 75%, rgba(255, 118, 117, 0.15) 0%, transparent 70%);
            }
            
            .container {
                min-height: 100vh;
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
                padding: 2rem;
                position: relative;
                max-width: 1200px;
                margin: 0 auto;
            }
            
            .header {
                text-align: center;
                margin-bottom: 4rem;
            }
            
            .logo {
                font-size: 3rem;
                font-weight: 700;
                background: linear-gradient(135deg, #7877C6 0%, #FF7675 100%);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
                background-clip: text;
                margin-bottom: 1rem;
                letter-spacing: -0.02em;
            }
            
            .tagline {
                font-size: 1.2rem;
                color: #7d8590;
                font-weight: 400;
                margin-bottom: 0.5rem;
            }
            
            .subtitle {
                font-size: 1rem;
                color: #656d76;
                font-weight: 300;
            }
            
            .error-section {
                text-align: center;
                margin-bottom: 4rem;
            }
            
            .error-code {
                font-size: 10rem;
                font-weight: 700;
                background: linear-gradient(135deg, #7877C6 0%, #FF7675 100%);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
                background-clip: text;
                margin-bottom: 1.5rem;
                line-height: 1;
                letter-spacing: -0.02em;
            }
            
            .error-message {
                font-size: 2rem;
                font-weight: 600;
                color: #e6edf3;
                margin-bottom: 1rem;
            }
            
            .error-description {
                font-size: 1.1rem;
                color: #7d8590;
                max-width: 600px;
                margin: 0 auto 2.5rem;
                line-height: 1.7;
            }
            
            
            .vision-section {
                margin-top: 6rem;
                text-align: center;
                max-width: 800px;
                width: 100%;
                position: relative;
            }
            
            .vision-content {
                position: relative;
                z-index: 2;
            }
            
            .vision-title {
                font-size: 1.5rem;
                font-weight: 700;
                color: #FF7675;
                margin-bottom: 1.5rem;
                letter-spacing: 0.1em;
                text-transform: uppercase;
                position: relative;
            }
            
            .vision-text {
                font-size: 1.3rem;
                color: #e6edf3;
                font-weight: 400;
                line-height: 1.8;
                opacity: 0.9;
                max-width: 600px;
                margin: 0 auto;
            }
            
            .vision-decoration {
                display: flex;
                align-items: center;
                justify-content: center;
                margin-top: 3rem;
                opacity: 0.6;
            }
            
            .decoration-line {
                width: 80px;
                height: 1px;
                background: linear-gradient(90deg, transparent, #7877C6, transparent);
            }
            
            .decoration-dot {
                width: 8px;
                height: 8px;
                background: linear-gradient(135deg, #7877C6 0%, #FF7675 100%);
                border-radius: 50%;
                margin: 0 1rem;
                box-shadow: 0 0 20px rgba(120, 119, 198, 0.5);
            }
            
            .breadcrumb {
                position: absolute;
                top: 2rem;
                left: 2rem;
                font-size: 0.9rem;
                color: #7d8590;
            }
            
            
            
            @media (max-width: 768px) {
                .error-code {
                    font-size: 7rem;
                }
                
                .logo {
                    font-size: 2.5rem;
                }
                
                .error-message {
                    font-size: 1.5rem;
                }
                
                
                .vision-title {
                    font-size: 1.3rem;
                }
                
                .vision-text {
                    font-size: 1.1rem;
                }
                
                .breadcrumb {
                    position: static;
                    margin-bottom: 2rem;
                }
            }
        </style>
    </head>
    <body>
        <div class="background"></div>
        
        <div class="breadcrumb">
            XQUARE Infrastructure / 404 Error
        </div>
        
        
        <div class="container">
            <div class="header">
                <div class="logo">XQUARE</div>
                <div class="tagline">DSM을 위한 통합 인프라 서비스</div>
                <div class="subtitle">Production-Ready Infrastructure Platform</div>
            </div>
            
            <div class="error-section">
                <div class="error-code">404</div>
                <div class="error-message">서비스를 찾을 수 없습니다</div>
                <div class="error-description">
                    요청하신 서비스가 아직 배포되지 않았거나 존재하지 않습니다.<br>
                    서비스 배포 상태를 확인하고 다시 시도해주세요.
                </div>
            </div>
            
            <div class="vision-section">
                <div class="vision-content">
                    <div class="vision-title">VISION</div>
                    <div class="vision-text">
                        모든 학생 개발자가 운영 환경 걱정 없이<br>
                        서비스의 성장에만 집중할 수 있는 세상을 만듭니다.
                    </div>
                </div>
                <div class="vision-decoration">
                    <div class="decoration-line"></div>
                    <div class="decoration-dot"></div>
                    <div class="decoration-line"></div>
                </div>
            </div>
        </div>
    </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-404-nginx-config
  namespace: {{ .Release.Namespace | default "default" }}
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        error_page 404 /index.html;
    }
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: custom-404-route
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  parentRefs:
  - name: external-gateway
    namespace: {{ .Release.Namespace | default "default" }}
  {{- if .Values.internal.enabled }}
  - name: internal-gateway
    namespace: {{ .Release.Namespace | default "default" }}
  {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/"
    backendRefs:
    - name: custom-404-service
      port: 80
{{- end }}