{{- if .Values.internal.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal-gateway
  namespace: {{ .Release.Namespace | default "default" }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  gatewayClassName: cilium
  # infrastructure:
  #   annotations:
  #     io.cilium/lb-ipam-ips: {{ .Values.internal.ip }}
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    hostname: "*.dsmhs.kr"
    allowedRoutes:
      namespaces:
        from: All
  - name: https
    port: 443
    protocol: HTTPS
    hostname: "*.dsmhs.kr"
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
        - name: wildcard-dsmhs-tls
{{- end }}