apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2-policy
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  loadBalancerIPs: true
  interfaces:
  - "^eth[0-9]+"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: default-pool
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  cidrs:
  - cidr: {{ .Values.ippool.cidr }}