apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2-policy
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  loadBalancerIPs: true
  externalIPs: true
  interfaces:
    - "^eno[0-9]+"
{{/*  prefixLength: 24*/}}
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: default-pool
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  blocks:
    - start: {{ .Values.ippool.start | quote }}
      stop: {{ .Values.ippool.stop | quote }}
  serviceSelector:
    matchLabels:
      "io.kubernetes.service.namespace": {{ .Release.Namespace | default "default" | quote }}