apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-resource-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/team-xquare/xquare-onpremise-k8s-resource.git
        revision: HEAD
        directories:
          - path: charts/*
  template:
    metadata:
      name: "{{path.basename}}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/team-xquare/xquare-onpremise-k8s-resource.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - PruneLast=true
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
          - ApplyOutOfSyncOnly=true
          - Validate=true
