apiVersion: v2
name: cloudflare-tunnel-remote
description: Cloudflare Tunnel chart for Kubernetes
type: application
version: 1.0.0
dependencies:
  - name: cloudflare-tunnel-remote
    version: "0.1.2"
    repository: "https://cloudflare.github.io/helm-charts"
