cloudflare-tunnel-remote:
  cloudflare:
    tunnel_token: <path:avp/data/cloudflare-tunnel-remote/#tunnel_token>

  replicaCount: 7

  image:
    repository: cloudflare/cloudflared
    pullPolicy: IfNotPresent
    tag: "latest"

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: In
                values:
                  - "cloudflare-tunnel"
          topologyKey: "kubernetes.io/hostname"
