cloudflare-tunnel-remote:
  cloudflare:
    tunnel_token: <path:avp/data/cloudflare-tunnel-remote/#tunnel_token>
  replicaCount: 3

  image:
    repository: cloudflare/cloudflared
    pullPolicy: IfNotPresent
    tag: "latest"
