cloudflare-tunnel-remote:
  cloudflare:
    tunnel_token: <path:avp/data/cloudflare-tunnel-remote/#tunnel_token>

  replicaCount: 4

  image:
    repository: cloudflare/cloudflared
    pullPolicy: IfNotPresent
    tag: "latest"

  tolerations:
    - operator: "Exists"

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: "pod"
                operator: In
                values:
                  - "cloudflared"
          topologyKey: "kubernetes.io/hostname"
