apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: longhorn-server
  namespace: longhorn-system
spec:
  parentRefs:
    - name: internal-gateway
      namespace: gateway
  hostnames:
    - longhorn-xquare-infra.dsmhs.kr.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: longhorn-frontend
          port: 80
