cloudflare-tunnel:
  cloudflare:
    secretName: "cloudflare-tunnel-secret"

    tunnelName: "xquare-onpremise"

    enableWarp: true

    ingress:

  replicaCount: 1

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
