cloudflare-tunnel:
  cloudflare:
    secretName: "cloudflare-tunnel-secret"

    tunnelName: "xquare-onpremise"

    enableWarp: true

    ingress:
      - hostname: "*.dsmhs.kr"
        service: https://192.168.0.200:443

      - hostname: "dsmhs.kr"
        service: https://192.168.0.200:443

  replicaCount: 2

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65532

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
