apiVersion: v2
name: kube-prometheus-stack
description: Grafana and Prometheus of Kubernetes
type: application
version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: "75.6.2"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: prometheus-smartctl-exporter
    version: "0.15.3"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: smartctl-exporter.enabled
  - name: prometheus-ipmi-exporter
    version: "0.6.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: ipmi-exporter.enabled