kube-prometheus-stack:
  crds:
    enabled: true

  nodeExporter:
    enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 30Mi
      limits:
        cpu: 50m
        memory: 50Mi
    tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

  prometheusOperator:
    enabled: true
    resources:
      requests:
        cpu: 200m
        memory: 300Mi
      limits:
        cpu: 500m
        memory: 600Mi

  kubeStateMetrics:
    enabled: true
    resources:
      requests:
        cpu: 20m
        memory: 80Mi
      limits:
        cpu: 60m
        memory: 150Mi

  prometheus:
    enabled: true
    ingress:
      enabled: false
    prometheusSpec:
      serviceMonitorSelector: {}
      ruleSelector: {}
      resources:
        requests:
          cpu: 500m
          memory: 4Gi
        limits:
          cpu: 1200m
          memory: 8Gi
      storageSpec:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 50Gi

  alertmanager:
    enabled: true
    alertmanagerSpec:
      resources:
        requests:
          cpu: 25m
          memory: 80Mi
        limits:
          cpu: 150m
          memory: 200Mi
      storage:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 15Gi

  grafana:
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
      limits:
        cpu: 300m
        memory: 600Mi
    persistence:
      enabled: true
      size: 25Gi
    ingress:
      enabled: false
    grafana.ini:
      auth:
        disable_login_form: true
      auth.anonymous:
        enabled: true
        org_role: Admin
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki-stack.loki-stack.svc.cluster.local:3100

prometheus-smartctl-exporter:
  enabled: true
  resources:
    requests:
      cpu: 15m
      memory: 30Mi
    limits:
      cpu: 60m
      memory: 60Mi
  serviceMonitor:
    enabled: true
  securityContext:
    privileged: true

prometheus-ipmi-exporter:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 30Mi
    limits:
      cpu: 40m
      memory: 60Mi
  serviceMonitor:
    enabled: true
  securityContext:
    privileged: true
    hostNetwork: true
