kube-prometheus-stack:
  crds:
    enabled: true

  nodeExporter:
    enabled: true
    tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

  prometheusOperator:
    enabled: true
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    tolerations:
      - key: "role"
        operator: "Equal"
        value: "monitoring"
        effect: "NoSchedule"
    nodeSelector:
      role: monitoring

  kubeStateMetrics:
    enabled: true
    tolerations:
      - key: "role"
        operator: "Equal"
        value: "monitoring"
        effect: "NoSchedule"
    nodeSelector:
      role: monitoring

  prometheus:
    enabled: true
    ingress:
      enabled: false
    prometheusSpec:
      serviceMonitorSelector: {}
      ruleSelector: {}
      resources:
        requests:
          cpu: 350m
          memory: 5Gi
        limits:
          cpu: 400m
          memory: 7Gi
      storageSpec:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 20Gi
      tolerations:
        - key: "role"
          operator: "Equal"
          value: "monitoring"
          effect: "NoSchedule"
      nodeSelector:
        role: monitoring

  alertmanager:
    enabled: true
    alertmanagerSpec:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
      storage:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 5Gi
      tolerations:
        - key: "role"
          operator: "Equal"
          value: "monitoring"
          effect: "NoSchedule"
      nodeSelector:
        role: monitoring

  grafana:
    enabled: true

    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi

    persistence:
      enabled: true
      size: 10Gi

    ingress:
      enabled: false

    tolerations:
      - key: "role"
        operator: "Equal"
        value: "monitoring"
        effect: "NoSchedule"

    nodeSelector:
      role: monitoring

    grafana.ini:
      auth:
        disable_login_form: true
      auth.anonymous:
        enabled: true
        org_role: Admin

    additionalDataSources:
      - name: Prometheus
        type: prometheus
        url: http://kube-prometheus-stack-prometheus:9090
        access: proxy
        isDefault: false
      - name: Alertmanager
        type: alertmanager
        url: http://kube-prometheus-stack-alertmanager:9093
        access: proxy
        editable: false