kube-prometheus-stack:
  crds:
    enabled: true

  nodeExporter:
    enabled: true

  prometheusOperator:
    enabled: true
    resources:
      requests:
        cpu: 1m
        memory: 16Mi
      limits:
        cpu: 2m
        memory: 20Mi

  kubeStateMetrics:
    enabled: true

  prometheus:
    enabled: true
    ingress:
      enabled: false
    prometheusSpec:
      serviceMonitorSelector: {}
      ruleSelector: {}
      resources:
        requests:
          cpu: 350m
          memory: 5Gi
        limits:
          cpu: 400m
          memory: 7Gi
      storageSpec:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 20Gi

  alertmanager:
    enabled: true
    alertmanagerSpec:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
      storage:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 5Gi

  grafana:
    enabled: true

    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 15m
        memory: 256Mi

    persistence:
      enabled: true
      size: 10Gi

    ingress:
      enabled: false

    grafana.ini:
      auth:
        disable_login_form: true
      auth.anonymous:
        enabled: true
        org_role: Admin

    additionalDataSources:
      - name: Prometheus
        type: prometheus
        url: http://kube-prometheus-stack-prometheus:9090
        access: proxy
        isDefault: true
      - name: Alertmanager
        type: alertmanager
        url: http://kube-prometheus-stack-alertmanager:9093
        access: proxy
        editable: false