loki-stack:
  loki:
    enabled: true
    persistence:
      enabled: true
      size: 30Gi
    config:
      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
      schema_config:
        configs:
          - from: 2025-01-16
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h
    resources:
      requests:
        cpu: 200m
        memory: 400Mi
      limits:
        cpu: 600m
        memory: 1Gi

  promtail:
    enabled: true
    resources:
      requests:
        cpu: 80m
        memory: 200Mi
      limits:
        cpu: 250m
        memory: 400Mi
    tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
  grafana:
    enabled: false
  prometheus:
    enabled: false
  filebeat:
    enabled: false
  fluent-bit:
    enabled: false
  logstash:
    enabled: false
  serviceMonitor:
    enabled: true
