apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: vault-ui
  namespace: vault
spec:
  parentRefs:
    - name: internal-gateway
      namespace: gateway
  hostnames:
    - vault-xquare-infra.dsmhs.kr
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: vault-ui
          port: 8200
